project:
  type: website
  output-dir: docs

website:
  title: "Dmitrii Tereshchenko's Homepage"
  navbar:
    left:
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

