project:
  type: website
  output-dir: docs

website:
  title: "Dmitrii Tereshchenko's Homepage"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

